// This is an automatically generated file for the hbs template.
// You don't need to change it, run npm run build:hbs to update it.
/* istanbul ignore file */
/* tslint: disable */
/* eslint: disable */
// @ts-nocheck
export default {"compiler":[8,">= 4.3.0"],"main":function(container,depth0,helpers,partials,data) {
    var stack1, alias1=container.strict, alias2=container.lambda;

  return "/**\n * Avatar Service Wrapper\n * Automatically generated wrapper for "
    + ((stack1 = alias2(alias1(depth0, "serviceName", {"start":{"line":3,"column":41},"end":{"line":3,"column":52}} ), depth0)) != null ? stack1 : "")
    + " service\n * Integrates with swarm coordination and health monitoring\n */\n\nimport { "
    + ((stack1 = alias2(alias1(depth0, "swarmNameCamel", {"start":{"line":7,"column":11},"end":{"line":7,"column":25}} ), depth0)) != null ? stack1 : "")
    + "Coordinator, "
    + ((stack1 = alias2(alias1(depth0, "swarmNameCamel", {"start":{"line":7,"column":42},"end":{"line":7,"column":56}} ), depth0)) != null ? stack1 : "")
    + "ServiceRegistry } from '../coordinator';\n\nexport interface AvatarServiceConfig {\n  serviceId: string;\n  baseURL: string;\n  timeout: number;\n  retryPolicy: {\n    maxRetries: number;\n    initialDelayMs: number;\n  };\n}\n\n/**\n * Avatar wrapper for "
    + ((stack1 = alias2(alias1(depth0, "serviceName", {"start":{"line":20,"column":24},"end":{"line":20,"column":35}} ), depth0)) != null ? stack1 : "")
    + " service\n */\nexport class "
    + ((stack1 = alias2(alias1(depth0, "serviceName", {"start":{"line":22,"column":15},"end":{"line":22,"column":26}} ), depth0)) != null ? stack1 : "")
    + "Avatar {\n  private readonly config: AvatarServiceConfig;\n  private readonly client: any; // Real service client\n  private requestCount: number = 0;\n  private errorCount: number = 0;\n  private healthCheckInterval: NodeJS.Timeout | null = null;\n\n  constructor(\n    config: AvatarServiceConfig,\n    client: any\n  ) {\n    this.config = config;\n    this.client = client;\n\n    // Register with coordinator\n    "
    + ((stack1 = alias2(alias1(depth0, "swarmNameCamel", {"start":{"line":37,"column":6},"end":{"line":37,"column":20}} ), depth0)) != null ? stack1 : "")
    + "Coordinator.registerService(config.serviceId);\n\n    // Start health monitoring\n    this.startHealthMonitoring();\n  }\n\n  /**\n   * Execute operation with retry logic and monitoring\n   */\n  public async executeOperation<T>(\n    operationName: string,\n    params: any\n  ): Promise<T> {\n    const retryPolicy = this.config.retryPolicy;\n    let lastError: any;\n\n    for (let attempt = 0; attempt <= retryPolicy.maxRetries; attempt++) {\n      try {\n        this.requestCount++;\n\n        // Call actual service\n        const result = await Promise.race([\n          this.client[operationName](params),\n          this.createTimeout(),\n        ]);\n\n        return result;\n      } catch (error) {\n        lastError = error;\n        this.errorCount++;\n\n        if (attempt < retryPolicy.maxRetries) {\n          const delay = retryPolicy.initialDelayMs * Math.pow(2, attempt);\n          await this.sleep(delay);\n        }\n      }\n    }\n\n    throw lastError;\n  }\n\n  /**\n   * Get service metrics\n   */\n  public getMetrics() {\n    return {\n      serviceId: this.config.serviceId,\n      totalRequests: this.requestCount,\n      totalErrors: this.errorCount,\n      errorRate: this.requestCount > 0 ? this.errorCount / this.requestCount : 0,\n      health: this.errorCount / Math.max(this.requestCount, 1) < 0.05 ? 'healthy' : 'degraded',\n    };\n  }\n\n  /**\n   * Health check\n   */\n  public async healthCheck(): Promise<boolean> {\n    try {\n      // Would call health endpoint\n      return true;\n    } catch {\n      return false;\n    }\n  }\n\n  /**\n   * Start periodic health monitoring\n   */\n  private startHealthMonitoring(): void {\n    this.healthCheckInterval = setInterval(() => {\n      this.healthCheck();\n    }, 60000);\n  }\n\n  /**\n   * Stop health monitoring\n   */\n  public shutdown(): void {\n    if (this.healthCheckInterval) {\n      clearInterval(this.healthCheckInterval);\n    }\n  }\n\n  /**\n   * Helper: create timeout promise\n   */\n  private createTimeout(): Promise<never> {\n    return new Promise((_, reject) =>\n      setTimeout(() => reject(new Error('Request timeout')), this.config.timeout)\n    );\n  }\n\n  /**\n   * Helper: sleep\n   */\n  private sleep(ms: number): Promise<void> {\n    return new Promise(resolve => setTimeout(resolve, ms));\n  }\n}\n\n/**\n * Avatar group for managing multiple instances\n */\nexport class "
    + ((stack1 = alias2(alias1(depth0, "serviceName", {"start":{"line":141,"column":15},"end":{"line":141,"column":26}} ), depth0)) != null ? stack1 : "")
    + "AvatarGroup {\n  private avatars: Map<string, "
    + ((stack1 = alias2(alias1(depth0, "serviceName", {"start":{"line":142,"column":33},"end":{"line":142,"column":44}} ), depth0)) != null ? stack1 : "")
    + "Avatar>;\n  private rrIndex: number = 0;\n\n  constructor() {\n    this.avatars = new Map();\n  }\n\n  /**\n   * Add avatar to group\n   */\n  public addAvatar(avatar: "
    + ((stack1 = alias2(alias1(depth0, "serviceName", {"start":{"line":152,"column":29},"end":{"line":152,"column":40}} ), depth0)) != null ? stack1 : "")
    + "Avatar, instanceId: string): void {\n    this.avatars.set(instanceId, avatar);\n  }\n\n  /**\n   * Execute operation on best available avatar\n   */\n  public async executeOnBest<T>(\n    operationName: string,\n    params: any\n  ): Promise<T> {\n    const healthyAvatars = Array.from(this.avatars.values()).filter(\n      a => a.getMetrics().health === 'healthy'\n    );\n\n    if (healthyAvatars.length === 0) {\n      throw new Error('No healthy avatars available');\n    }\n\n    const selected = healthyAvatars[this.rrIndex % healthyAvatars.length];\n    this.rrIndex = (this.rrIndex + 1) % healthyAvatars.length;\n    return selected.executeOperation(operationName, params);\n  }\n\n  /**\n   * Get group metrics\n   */\n  public getGroupMetrics(): any {\n    const metrics = Array.from(this.avatars.values()).map(a => a.getMetrics());\n    const totalRequests = metrics.reduce((sum, m) => sum + m.totalRequests, 0);\n    const totalErrors = metrics.reduce((sum, m) => sum + m.totalErrors, 0);\n\n    return {\n      instanceCount: this.avatars.size,\n      healthyCount: metrics.filter(m => m.health === 'healthy').length,\n      totalRequests,\n      totalErrors,\n      overallErrorRate: totalRequests > 0 ? totalErrors / totalRequests : 0,\n    };\n  }\n\n  /**\n   * Shutdown all avatars\n   */\n  public shutdownAll(): void {\n    for (const avatar of this.avatars.values()) {\n      avatar.shutdown();\n    }\n    this.avatars.clear();\n  }\n}\n";
},"useData":true}