import { dirname, join } from 'path';

import { fileSystemHelpers } from '../../common/utils/fileSystemHelpers';
import { resolveHelper } from '../../common/utils/pathHelpers';
import type { TrafficSplitterConfig } from './types';

function buildTrafficSplitterSource(config: TrafficSplitterConfig): string {
    const configJson = JSON.stringify(config, null, 2);
    return `// AUTO-GENERATED by openapi-codegen — do not edit manually
// TrafficSplitter: standalone migration helper (no external dependencies)

type TrafficSplitterStrategy = 'weighted' | 'round-robin' | 'header-based' | 'header-and-weighted';

type TrafficSplitterConfig = {
    enabled?: boolean;
    strategy?: TrafficSplitterStrategy;
    oldClientWeight?: number;
    newClientWeight?: number;
    stickySessions?: boolean;
    sessionDuration?: string;
    headerName?: string;
    headerValues?: { old: string; new: string };
};

type TrafficSplittingResult = {
    isNewClient: boolean;
};

type SessionStats = {
    totalRequests: number;
    newClientRequests: number;
    oldClientRequests: number;
    stickySessionHits: number;
};

type StickySession = {
    isNewClient: boolean;
    expiresAt: number;
};

function parseDurationMs(duration: string): number {
    const match = /^(\\d+)(ms|s|m|h|d)$/.exec(duration.trim());
    if (!match) return 3600000;
    const value = parseInt(match[1], 10);
    const unit = match[2];
    const multipliers: Record<string, number> = { ms: 1, s: 1000, m: 60000, h: 3600000, d: 86400000 };
    return value * (multipliers[unit] ?? 1000);
}

function hashClientId(clientId: string): number {
    let hash = 0;
    for (let i = 0; i < clientId.length; i++) {
        hash = (hash * 31 + clientId.charCodeAt(i)) & 0xffffffff;
    }
    return Math.abs(hash);
}

export class TrafficSplitter {
    private readonly config: TrafficSplitterConfig;
    private roundRobinCounter = 0;
    private readonly stickySessions = new Map<string, StickySession>();
    private readonly stats: SessionStats = {
        totalRequests: 0,
        newClientRequests: 0,
        oldClientRequests: 0,
        stickySessionHits: 0,
    };

    constructor(config?: Partial<TrafficSplitterConfig>) {
        this.config = { ...${configJson}, ...config };
    }

    routeRequest(params: { clientId?: string; headers?: Record<string, string> }): TrafficSplittingResult {
        const { clientId = '', headers = {} } = params;
        this.stats.totalRequests++;

        if (this.config.stickySessions && clientId) {
            const existing = this.stickySessions.get(clientId);
            if (existing && existing.expiresAt > Date.now()) {
                this.stats.stickySessionHits++;
                return { isNewClient: existing.isNewClient };
            }
        }

        const isNewClient = this.resolveRoute(clientId, headers);

        if (this.config.stickySessions && clientId) {
            const ttl = parseDurationMs(this.config.sessionDuration ?? '1h');
            this.stickySessions.set(clientId, { isNewClient, expiresAt: Date.now() + ttl });
        }

        if (isNewClient) {
            this.stats.newClientRequests++;
        } else {
            this.stats.oldClientRequests++;
        }

        return { isNewClient };
    }

    private resolveRoute(clientId: string, headers: Record<string, string>): boolean {
        const strategy = this.config.strategy ?? 'weighted';
        switch (strategy) {
            case 'weighted':
                return this.weightedRoute(clientId);
            case 'round-robin':
                return this.roundRobinRoute();
            case 'header-based':
                return this.headerBasedRoute(headers);
            case 'header-and-weighted': {
                const result = this.headerBasedRouteOrNull(headers);
                return result !== null ? result : this.weightedRoute(clientId);
            }
        }
    }

    private weightedRoute(clientId: string): boolean {
        const weight = this.config.newClientWeight ?? 50;
        return hashClientId(clientId) % 100 < weight;
    }

    private roundRobinRoute(): boolean {
        const result = this.roundRobinCounter % 2 === 1;
        this.roundRobinCounter++;
        return result;
    }

    private headerBasedRoute(headers: Record<string, string>): boolean {
        return this.headerBasedRouteOrNull(headers) ?? false;
    }

    private headerBasedRouteOrNull(headers: Record<string, string>): boolean | null {
        const headerName = this.config.headerName;
        if (!headerName) return null;
        const headerValue = headers[headerName] ?? headers[headerName.toLowerCase()];
        if (headerValue === undefined) return null;
        const newValue = this.config.headerValues?.new;
        return newValue !== undefined ? headerValue === newValue : false;
    }

    getStats(): SessionStats {
        return { ...this.stats };
    }
}
`;
}

export async function generateTrafficSplitterModule(config: TrafficSplitterConfig, outputPath: string): Promise<void> {
    const absoluteOutput = resolveHelper(process.cwd(), outputPath);
    const filePath = join(absoluteOutput, 'TrafficSplitter.ts');
    await fileSystemHelpers.mkdir(dirname(filePath));
    await fileSystemHelpers.writeFile(filePath, buildTrafficSplitterSource(config));
}
