import * as fs from 'fs';
import * as path from 'path';

/**
 * Генерирует самодостаточный модуль TrafficSplitter для вывода migrate.
 * @returns исходный код TrafficSplitter с inline-типами
 */
export function generateTrafficSplitterModule(): string {
    const typesBlock = `export interface TrafficSplitterConfig {
  enabled?: boolean;
  strategy?: 'round-robin' | 'weighted' | 'header-based' | 'header-and-weighted';
  oldClientWeight?: number;
  newClientWeight?: number;
  headerName?: string;
  headerValues?: { old: string; new: string };
  stickySessions?: boolean;
  sessionDuration?: string;
}

export interface TrafficSplittingResult {
  clientKey: string;
  isNewClient: boolean;
  weight: number;
  reason: string;
}
`;

    const splitterPath = path.join(__dirname, 'TrafficSplitter.ts');
    let splitterSource = fs.readFileSync(splitterPath, 'utf-8');
    splitterSource = splitterSource.replace(/^import .* from '\.\/types';\n/m, '');

    return `/* {{autogenerated}} */
/**
 * Traffic splitter runtime helper generated by openapi-codegen migrate.
 */

${typesBlock}
${splitterSource.trim()}
`;
}
