import { MigrationPlan, TrafficSplitterConfig } from './types';

export interface MigrationRuntimeGeneratorOptions {
    /** Имя или метка legacy-клиента */
    fromClient: string;
    /** Имя или метка целевого клиента */
    toClient: string;
    /** План поэтапной миграции */
    plan: MigrationPlan;
    /** [trafficConfig] переопределение стратегии сплита трафика */
    trafficConfig?: Partial<TrafficSplitterConfig>;
}

/**
 * Генерирует migration runtime helper — обёртку над TrafficSplitter для old/new клиентов.
 * @param options параметры генерации helper
 * @returns исходный код TypeScript-модуля
 */
export function generateMigrationRuntimeHelper(options: MigrationRuntimeGeneratorOptions): string {
    const { fromClient, toClient, plan, trafficConfig } = options;
    const initialPhase = plan.phases[0];
    const oldWeight = initialPhase ? Math.round(initialPhase.traffic.old * 100) : (trafficConfig?.oldClientWeight ?? 50);
    const newWeight = initialPhase ? Math.round(initialPhase.traffic.new * 100) : (trafficConfig?.newClientWeight ?? 50);
    const strategy = trafficConfig?.strategy ?? 'weighted';
    const headerName = trafficConfig?.headerName ?? 'X-Migration-Client';
    const headerOld = trafficConfig?.headerValues?.old ?? 'old';
    const headerNew = trafficConfig?.headerValues?.new ?? 'new';

    return `/* {{autogenerated}} */
/**
 * Migration runtime helper: ${fromClient} → ${toClient}
 * Strategy: ${plan.strategy}
 * Generated by openapi-codegen migrate — wire your client instances and call routeRequest().
 */

import { TrafficSplitter, TrafficSplitterConfig, TrafficSplittingResult } from './TrafficSplitter';

export type MigrationClientKey = 'old' | 'new';

export interface MigrationRuntimeConfig extends Partial<TrafficSplitterConfig> {
  /** Instance of the legacy (${fromClient}) client */
  oldClient: unknown;
  /** Instance of the target (${toClient}) client */
  newClient: unknown;
}

export class MigrationRuntimeClient {
  private readonly splitter = new TrafficSplitter();
  private readonly config: MigrationRuntimeConfig;
  private readonly trafficConfig: Partial<TrafficSplitterConfig>;

  constructor(config: MigrationRuntimeConfig) {
    this.config = config;
    this.trafficConfig = {
      enabled: true,
      strategy: '${strategy}',
      oldClientWeight: ${oldWeight},
      newClientWeight: ${newWeight},
      headerName: '${headerName}',
      headerValues: { old: '${headerOld}', new: '${headerNew}' },
      stickySessions: ${trafficConfig?.stickySessions !== false ? 'true' : 'false'},
      sessionDuration: '${trafficConfig?.sessionDuration ?? '1h'}',
      ...config,
    };
  }

  /**
   * Resolve which client should handle a request.
   */
  routeRequest(
    clientId: string,
    requestHeaders?: Record<string, string>
  ): TrafficSplittingResult {
    return this.splitter.routeRequest(clientId, this.trafficConfig, requestHeaders);
  }

  /**
   * Return the active client instance for a routed request.
   */
  getClientForRoute(route: TrafficSplittingResult): unknown {
    return route.isNewClient ? this.config.newClient : this.config.oldClient;
  }

  /**
   * Execute a method on the routed client.
   */
  async execute<T>(
    clientId: string,
    fn: (client: unknown) => Promise<T>,
    requestHeaders?: Record<string, string>
  ): Promise<T> {
    const route = this.routeRequest(clientId, requestHeaders);
    const client = this.getClientForRoute(route);
    return fn(client);
  }

  getSessionStats() {
    return this.splitter.getSessionStats();
  }
}
`;
}
