// This is an automatically generated file for the hbs template.
// You don't need to change it, run npm run build:hbs to update it.
/* istanbul ignore file */
/* tslint: disable */
/* eslint: disable */
// @ts-nocheck
export default {"1":function(container,depth0,helpers,partials,data) {
    return "import { CancelablePromise } from './CancelablePromise';\n";
},"3":function(container,depth0,helpers,partials,data) {
    return "export const customExecutor: RequestExecutor<MyCustomOptions> = {\n    request<TResponse>(config: RequestConfig, options?: MyCustomOptions): CancelablePromise<TResponse> {\n        return new CancelablePromise(async (resolve, reject, onCancel) => {\n            try {\n                const abortController = new AbortController();\n                if (options?.timeout) {\n                    const timeoutId = setTimeout(() => abortController.abort(), options.timeout);\n                    onCancel(() => clearTimeout(timeoutId));\n                }\n                onCancel(() => abortController.abort());\n\n                const response = await fetch(buildUrl(config), {\n                    method: config.method,\n                    headers: config.headers,\n                    body: config.body ? JSON.stringify(config.body) : undefined,\n                    signal: abortController.signal,\n                });\n\n                if (!response.ok) {\n                    throw new Error(`Request failed: ${response.status} ${response.statusText}`);\n                }\n\n                resolve((await response.json()) as TResponse);\n            } catch (error) {\n                reject(error);\n            }\n        });\n    },\n\n    requestRaw<TResponse>(config: RequestConfig, options?: MyCustomOptions): CancelablePromise<ApiResult<TResponse>> {\n        return new CancelablePromise(async (resolve, reject, onCancel) => {\n            try {\n                const abortController = new AbortController();\n                if (options?.timeout) {\n                    const timeoutId = setTimeout(() => abortController.abort(), options.timeout);\n                    onCancel(() => clearTimeout(timeoutId));\n                }\n                onCancel(() => abortController.abort());\n\n                const url = buildUrl(config);\n                const response = await fetch(url, {\n                    method: config.method,\n                    headers: config.headers,\n                    body: config.body ? JSON.stringify(config.body) : undefined,\n                    signal: abortController.signal,\n                });\n\n                const body = (await response.json().catch(() => null)) as TResponse;\n                resolve({\n                    url,\n                    ok: response.ok,\n                    status: response.status,\n                    statusText: response.statusText,\n                    body,\n                });\n            } catch (error) {\n                reject(error);\n            }\n        });\n    },\n};\n";
},"5":function(container,depth0,helpers,partials,data) {
    return "export const customExecutor: RequestExecutor<MyCustomOptions> = {\n    async request<TResponse>(config: RequestConfig, options?: MyCustomOptions): Promise<TResponse> {\n        const response = await fetch(buildUrl(config), {\n            method: config.method,\n            headers: config.headers,\n            body: config.body ? JSON.stringify(config.body) : undefined,\n            signal: options?.timeout ? AbortSignal.timeout(options.timeout) : undefined,\n        });\n\n        if (!response.ok) {\n            throw new Error(`Request failed: ${response.status} ${response.statusText}`);\n        }\n\n        return response.json() as Promise<TResponse>;\n    },\n\n    async requestRaw<TResponse>(config: RequestConfig, options?: MyCustomOptions): Promise<ApiResult<TResponse>> {\n        const url = buildUrl(config);\n        const response = await fetch(url, {\n            method: config.method,\n            headers: config.headers,\n            body: config.body ? JSON.stringify(config.body) : undefined,\n            signal: options?.timeout ? AbortSignal.timeout(options.timeout) : undefined,\n        });\n\n        const body = (await response.json().catch(() => null)) as TResponse;\n        return {\n            url,\n            ok: response.ok,\n            status: response.status,\n            statusText: response.statusText,\n            body,\n        };\n    },\n};\n";
},"compiler":[8,">= 4.3.0"],"main":function(container,depth0,helpers,partials,data) {
    var stack1, alias1=depth0 != null ? depth0 : (container.nullContext || {}), lookupProperty = container.lookupProperty || function(parent, propertyName) {
        if (Object.prototype.hasOwnProperty.call(parent, propertyName)) {
          return parent[propertyName];
        }
        return undefined
    };

  return ((stack1 = container.invokePartial(lookupProperty(partials,"header"),depth0,{"name":"header","data":data,"helpers":helpers,"partials":partials,"decorators":container.decorators})) != null ? stack1 : "")
    + "\nimport type { ApiResult } from './ApiResult';\nimport type { TOpenAPIConfig } from './OpenAPI';\nimport { OpenAPI } from './OpenAPI';\nimport type { RequestExecutor, RequestConfig } from './executor/requestExecutor';\n"
    + ((stack1 = lookupProperty(helpers,"if").call(alias1,lookupProperty(depth0,"useCancelableRequest"),{"name":"if","hash":{},"fn":container.program(1, data, 0),"inverse":container.noop,"data":data,"loc":{"start":{"line":7,"column":0},"end":{"line":9,"column":7}}})) != null ? stack1 : "")
    + "\n/**\n * Typed per-request options (customize as needed).\n */\nexport interface MyCustomOptions {\n    timeout?: number;\n    retries?: number;\n}\n\nfunction buildUrl(config: RequestConfig, openApiConfig: TOpenAPIConfig = OpenAPI): string {\n    const path = config.path.replace('{api-version}', openApiConfig.VERSION);\n    return `${openApiConfig.BASE}${path}`;\n}\n\n/**\n * Custom RequestExecutor for direct service injection:\n *   const service = new SimpleService<MyCustomOptions>(customExecutor);\n *\n * For createClient integration use customExecutorPath with createExecutorAdapter scaffold instead.\n */\n"
    + ((stack1 = lookupProperty(helpers,"if").call(alias1,lookupProperty(depth0,"useCancelableRequest"),{"name":"if","hash":{},"fn":container.program(3, data, 0),"inverse":container.program(5, data, 0),"data":data,"loc":{"start":{"line":30,"column":0},"end":{"line":128,"column":7}}})) != null ? stack1 : "");
},"usePartial":true,"useData":true}