// This is an automatically generated file for the hbs template.
// You don't need to change it, run npm run build:hbs to update it.
/* istanbul ignore file */
/* tslint: disable */
/* eslint: disable */
// @ts-nocheck
export default {"1":function(container,depth0,helpers,partials,data) {
    return "import { CancelablePromise } from './CancelablePromise';\n";
},"3":function(container,depth0,helpers,partials,data) {
    return "export function request<T>(options: ApiRequestOptions, config: TOpenAPIConfig): CancelablePromise<T> {\n    return new CancelablePromise(async (resolve, reject, onCancel) => {\n        try {\n            const abortController = new AbortController();\n            onCancel(() => abortController.abort());\n\n            const url = buildUrl(options, config);\n            const response = await fetch(url, {\n                method: options.method,\n                headers: options.headers as HeadersInit,\n                body: options.body ? JSON.stringify(options.body) : undefined,\n                signal: abortController.signal,\n            });\n\n            const body = await response.json().catch(() => null);\n\n            if (!response.ok) {\n                throw new ApiError({\n                    status: response.status,\n                    message: response.statusText,\n                    body,\n                    request: toRequestConfig(options),\n                });\n            }\n\n            resolve(body as T);\n        } catch (error) {\n            reject(error);\n        }\n    });\n}\n\nexport function requestRaw<T>(options: ApiRequestOptions, config: TOpenAPIConfig): CancelablePromise<ApiResult<T>> {\n    return new CancelablePromise(async (resolve, reject, onCancel) => {\n        try {\n            const abortController = new AbortController();\n            onCancel(() => abortController.abort());\n\n            const url = buildUrl(options, config);\n            const response = await fetch(url, {\n                method: options.method,\n                headers: options.headers as HeadersInit,\n                body: options.body ? JSON.stringify(options.body) : undefined,\n                signal: abortController.signal,\n            });\n\n            const body = await response.json().catch(() => null);\n            const result: ApiResult<T> = {\n                url,\n                ok: response.ok,\n                status: response.status,\n                statusText: response.statusText,\n                body: body as T,\n            };\n\n            if (!response.ok) {\n                throw new ApiError({\n                    status: response.status,\n                    message: response.statusText,\n                    body,\n                    request: toRequestConfig(options),\n                });\n            }\n\n            resolve(result);\n        } catch (error) {\n            reject(error);\n        }\n    });\n}\n";
},"5":function(container,depth0,helpers,partials,data) {
    return "export async function request<T>(options: ApiRequestOptions, config: TOpenAPIConfig): Promise<T> {\n    const result = await requestRaw<T>(options, config);\n    return result.body;\n}\n\nexport async function requestRaw<T>(options: ApiRequestOptions, config: TOpenAPIConfig): Promise<ApiResult<T>> {\n    const url = buildUrl(options, config);\n    const response = await fetch(url, {\n        method: options.method,\n        headers: options.headers as HeadersInit,\n        body: options.body ? JSON.stringify(options.body) : undefined,\n    });\n\n    const body = await response.json().catch(() => null);\n    const result: ApiResult<T> = {\n        url,\n        ok: response.ok,\n        status: response.status,\n        statusText: response.statusText,\n        body: body as T,\n    };\n\n    if (!response.ok) {\n        throw new ApiError({\n            status: response.status,\n            message: response.statusText,\n            body,\n            request: toRequestConfig(options),\n        });\n    }\n\n    return result;\n}\n";
},"compiler":[8,">= 4.3.0"],"main":function(container,depth0,helpers,partials,data) {
    var stack1, alias1=depth0 != null ? depth0 : (container.nullContext || {}), lookupProperty = container.lookupProperty || function(parent, propertyName) {
        if (Object.prototype.hasOwnProperty.call(parent, propertyName)) {
          return parent[propertyName];
        }
        return undefined
    };

  return ((stack1 = container.invokePartial(lookupProperty(partials,"header"),depth0,{"name":"header","data":data,"helpers":helpers,"partials":partials,"decorators":container.decorators})) != null ? stack1 : "")
    + "\nimport { ApiError } from './ApiError';\nimport type { ApiRequestOptions } from './ApiRequestOptions';\nimport type { ApiResult } from './ApiResult';\nimport type { TOpenAPIConfig } from './OpenAPI';\n"
    + ((stack1 = lookupProperty(helpers,"if").call(alias1,lookupProperty(depth0,"useCancelableRequest"),{"name":"if","hash":{},"fn":container.program(1, data, 0),"inverse":container.noop,"data":data,"loc":{"start":{"line":7,"column":0},"end":{"line":9,"column":7}}})) != null ? stack1 : "")
    + "\n/**\n * Custom HTTP transport (legacy signature).\n * This file is copied to core/request.ts during generation.\n *\n * After generation, wrap it with createLegacyRequestAdapter from core/executor/legacyRequestAdapter.ts\n * or set \"request\" in openapi.config.json — createExecutorAdapter maps RequestConfig automatically.\n */\nfunction buildUrl(options: ApiRequestOptions, config: TOpenAPIConfig): string {\n    const path = options.path.replace('{api-version}', config.VERSION);\n    return `${config.BASE}${path}`;\n}\n\nfunction toRequestConfig(options: ApiRequestOptions): { method: string; path: string } {\n    return { method: options.method, path: options.path };\n}\n\n"
    + ((stack1 = lookupProperty(helpers,"if").call(alias1,lookupProperty(depth0,"useCancelableRequest"),{"name":"if","hash":{},"fn":container.program(3, data, 0),"inverse":container.program(5, data, 0),"data":data,"loc":{"start":{"line":27,"column":0},"end":{"line":132,"column":7}}})) != null ? stack1 : "");
},"usePartial":true,"useData":true}