openapi: 3.0.3
info:
  title: Document Management API
  version: 1.0.0
  description: API for managing documents and accounts
servers:
  - url: https://api.example.com/v1
paths:
  /documents/account:
    $ref: './specs/account.yaml'
  /documents/list:
    $ref: './specs/list.yaml'
  /documents/{id}:
    $ref: './specs/document.yaml'
  /documents/search:
    $ref: './specs/search.yaml'
components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        code:
          type: string
          example: ERR_INVALID_REQUEST
        message:
          type: string
          example: Invalid request parameters
      required:
        - code
        - message