import assert from 'node:assert';
import { describe, test } from 'node:test';

import * as Handlebars from 'handlebars/runtime';

import partialHeader from '../../../templatesCompiled/client/partials/header';
import { HttpClient } from '../../types/enums/HttpClient.enum';
import { registerHandlebarHelpers } from '../registerHandlebarHelpers';

const GENERATED_FILE_COMMENT = 'This file was automatically generated by the generator';

function renderHeaderPartial(useBatchEslintFix: boolean): string {
    registerHandlebarHelpers({
        httpClient: HttpClient.FETCH,
        useOptions: false,
        useUnionTypes: false,
        useBatchEslintFix,
    });
    Handlebars.registerPartial('header', Handlebars.template(partialHeader));
    return Handlebars.partials['header']({}) as string;
}

describe('@unit: registerHandlebarHelpers', () => {
    test('should register the helpers', () => {
        registerHandlebarHelpers({
            httpClient: HttpClient.FETCH,
            useOptions: false,
            useUnionTypes: false,
        });
        const helpers = Object.keys(Handlebars.helpers);
        assert.ok(helpers.some(item => item === 'equals'));
        assert.ok(helpers.some(item => item === 'notEquals'));
        assert.ok(helpers.some(item => item === 'containsSpaces'));
        assert.ok(helpers.some(item => item === 'union'));
        assert.ok(helpers.some(item => item === 'intersection'));
        assert.ok(helpers.some(item => item === 'useBatchEslintFix'));
    });

    test('header partial includes generated-file comment and disable directives when batch ESLint is off', () => {
        const output = renderHeaderPartial(false);

        assert.match(output, new RegExp(GENERATED_FILE_COMMENT));
        assert.match(output, /\/\* istanbul ignore file \*\//);
        assert.match(output, /\/\* tslint:disable \*\//);
        assert.match(output, /\/\* eslint-disable \*\//);
    });

    test('header partial omits disable directives when batch ESLint is on', () => {
        const output = renderHeaderPartial(true);

        assert.match(output, new RegExp(GENERATED_FILE_COMMENT));
        assert.match(output, /\/\* istanbul ignore file \*\//);
        assert.doesNotMatch(output, /tslint:disable/);
        assert.doesNotMatch(output, /eslint-disable/);
    });
});
