// This is an automatically generated file for the hbs template.
// You don't need to change it, run npm run build:hbs to update it.
/* istanbul ignore file */
/* tslint: disable */
/* eslint: disable */
// @ts-nocheck
export default {"compiler":[8,">= 4.3.0"],"main":function(container,depth0,helpers,partials,data) {
    var stack1;

  return "/* "
    + ((stack1 = container.lambda(container.strict(depth0, "autogenerated", {"start":{"line":1,"column":5},"end":{"line":1,"column":18}} ), depth0)) != null ? stack1 : "")
    + " */\n\n/**\n * Request deduplication middleware\n * Shares in-flight responses for identical concurrent requests\n */\n\nexport class RequestDeduplicator {\n  private inFlightRequests = new Map<string, Promise<any>>();\n\n  async deduplicate<T>(\n    key: string,\n    fn: () => Promise<T>\n  ): Promise<T> {\n    const existing = this.inFlightRequests.get(key);\n    if (existing) {\n      return existing as Promise<T>;\n    }\n\n    const promise = fn().finally(() => {\n      this.inFlightRequests.delete(key);\n    });\n\n    this.inFlightRequests.set(key, promise);\n    return promise;\n  }\n\n  getInFlightCount(): number {\n    return this.inFlightRequests.size;\n  }\n\n  clear(): void {\n    this.inFlightRequests.clear();\n  }\n}\n";
},"useData":true}