// This is an automatically generated file for the hbs template.
// You don't need to change it, run npm run build:hbs to update it.
/* istanbul ignore file */
/* tslint: disable */
/* eslint: disable */
// @ts-nocheck
export default {"compiler":[8,">= 4.3.0"],"main":function(container,depth0,helpers,partials,data) {
    var stack1;

  return "/* "
    + ((stack1 = container.lambda(container.strict(depth0, "autogenerated", {"start":{"line":1,"column":5},"end":{"line":1,"column":18}} ), depth0)) != null ? stack1 : "")
    + " */\n\n/**\n * Time-folding batcher\n * Buffers requests within a time window and flushes them as a batch\n */\n\nexport interface TimeFoldingConfig {\n  windowMs?: number;\n  maxBufferSize?: number;\n}\n\ninterface BufferedItem<T> {\n  item: T;\n  resolve: (value: T[]) => void;\n}\n\nexport class TimeFoldingBatcher<T = unknown> {\n  private buffer: BufferedItem<T>[] = [];\n  private flushTimer: ReturnType<typeof setTimeout> | null = null;\n  private readonly windowMs: number;\n  private readonly maxBufferSize: number;\n\n  constructor(config?: TimeFoldingConfig) {\n    this.windowMs = config?.windowMs ?? 100;\n    this.maxBufferSize = config?.maxBufferSize ?? 100;\n  }\n\n  async batch(item: T): Promise<T[]> {\n    return new Promise((resolve) => {\n      this.buffer.push({ item, resolve });\n\n      if (this.buffer.length >= this.maxBufferSize) {\n        this.flush();\n      } else if (!this.flushTimer) {\n        this.flushTimer = setTimeout(() => this.flush(), this.windowMs);\n      }\n    });\n  }\n\n  private flush(): void {\n    if (this.flushTimer) {\n      clearTimeout(this.flushTimer);\n      this.flushTimer = null;\n    }\n\n    if (this.buffer.length === 0) {\n      return;\n    }\n\n    const batch = this.buffer.splice(0);\n    const result = batch.map(entry => entry.item);\n    batch.forEach(entry => entry.resolve(result));\n  }\n\n  getBufferSize(): number {\n    return this.buffer.length;\n  }\n\n  dispose(): void {\n    if (this.flushTimer) {\n      clearTimeout(this.flushTimer);\n      this.flushTimer = null;\n    }\n    this.buffer = [];\n  }\n}\n";
},"useData":true}