// This is an automatically generated file for the hbs template.
// You don't need to change it, run npm run build:hbs to update it.
/* istanbul ignore file */
/* tslint: disable */
/* eslint: disable */
// @ts-nocheck
export default {"compiler":[8,">= 4.3.0"],"main":function(container,depth0,helpers,partials,data) {
    var stack1, lookupProperty = container.lookupProperty || function(parent, propertyName) {
        if (Object.prototype.hasOwnProperty.call(parent, propertyName)) {
          return parent[propertyName];
        }
        return undefined
    };

  return ((stack1 = container.invokePartial(lookupProperty(partials,"header"),depth0,{"name":"header","data":data,"helpers":helpers,"partials":partials,"decorators":container.decorators})) != null ? stack1 : "")
    + "\nimport type { ApiResult } from '../ApiResult';\nimport { RequestInterceptor, ResponseInterceptor, ErrorInterceptor } from './interceptors';\nimport { RequestConfig, RequestExecutor } from '../executor/requestExecutor';\n\nexport function withInterceptors<TOptions extends Record<string, any> = Record<string, never>>(\n    executor: RequestExecutor<TOptions>,\n    interceptors: {\n        onRequest?: RequestInterceptor[];\n        onResponse?: ResponseInterceptor[];\n        onError?: ErrorInterceptor[];\n    }\n): RequestExecutor<TOptions> {\n    const runRequestInterceptors = async (config: RequestConfig): Promise<RequestConfig> => {\n        let currentConfig = config;\n\n        for (const interceptor of interceptors.onRequest ?? []) {\n            currentConfig = await interceptor(currentConfig);\n        }\n\n        return currentConfig;\n    };\n\n    const runResponseInterceptors = async <TResponse>(\n        response: TResponse,\n        config: RequestConfig\n    ): Promise<TResponse> => {\n        let currentResponse = response;\n\n        for (const interceptor of interceptors.onResponse ?? []) {\n            currentResponse = (await interceptor(currentResponse, config)) as TResponse;\n        }\n\n        return currentResponse;\n    };\n\n    return {\n        async request<TResponse>(config: RequestConfig, options?: TOptions): Promise<TResponse> {\n            try {\n                const currentConfig = await runRequestInterceptors(config);\n                const response = await executor.request<TResponse>(currentConfig, options);\n\n                return runResponseInterceptors(response, currentConfig);\n            } catch (caught) {\n                let error = caught;\n                const currentConfig = config;\n\n                for (const interceptor of interceptors.onError ?? []) {\n                    error = await interceptor(error, currentConfig);\n                }\n\n                throw error;\n            }\n        },\n        async requestRaw<TResponse>(config: RequestConfig, options?: TOptions): Promise<ApiResult<TResponse>> {\n            try {\n                const currentConfig = await runRequestInterceptors(config);\n                const response = await executor.requestRaw<TResponse>(currentConfig, options);\n\n                return runResponseInterceptors(response, currentConfig);\n            } catch (caught) {\n                let error = caught;\n                const currentConfig = config;\n\n                for (const interceptor of interceptors.onError ?? []) {\n                    error = await interceptor(error, currentConfig);\n                }\n\n                throw error;\n            }\n        },\n    };\n}\n";
},"usePartial":true,"useData":true}